default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

development:
  <<: *default
  database: service_exchange_api_development

test:
  <<: *default
  database: service_exchange_api_test

production:
  <<: *default
  database: service_exchange_api_production
  username: rails_api
  password: <%= ENV['SERVICE_EXCHANGE_API_DB_PASS'] %>
